#!/usr/bin/env python3
"""Author the paper and review traceability inventories.

This script holds the *hand-curated* inventory data (one row per material paper method,
formula, figure, table, numeric claim, and review requirement) and writes both the
canonical machine-readable CSVs under ``manifests/`` and the human-readable markdown under
``docs/``. Edit the data here, then regenerate.

Column contract (paper): ``id, section, loc, item_type, description, stated_value,
legacy_producer, track_P_module, track_R_module, acceptance_test, tolerance, status``.
The three ``track_*`` / ``acceptance_test`` columns are *planned* targets (Phase 0 does not
claim the modules/tests exist yet), and ``status`` is ``planned`` until a later phase
implements the item. As of Phase 7 every review requirement (R-001..R-035) is implemented and
tested; the ``R_STATUS`` mapping below records which test module validates each row.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(_SRC))

from dwts_reproduction.config import load_paths  # noqa: E402

# --- Planned module taxonomy (coarse, refined in the owning phase) ---
PRE = "preprocessing"  # Phase 1
P1 = "problem1.model"  # Phase 2
P1E = "problem1.eval"  # Phase 3
P2 = "problem2.rules"  # Phase 2 replay
P2C = "problem2.cases"
P3 = "problem3.regression"
P4 = "problem4.mechanisms"
SEN = "sensitivity"
SHARED = "shared"

PAPER_HEADER = [
    "id",
    "section",
    "loc",
    "item_type",
    "description",
    "stated_value",
    "legacy_producer",
    "track_P_module",
    "track_R_module",
    "acceptance_test",
    "tolerance",
    "status",
]


def p(
    idx: int,
    section: str,
    loc: str,
    item_type: str,
    description: str,
    stated_value: str = "",
    producer: str = "",
    tp: str = "",
    tr: str = "",
    test: str = "",
    tol: str = "",
    status: str = "planned",
) -> list[str]:
    return [
        f"P-{idx:03d}",
        section,
        loc,
        item_type,
        description,
        stated_value,
        producer,
        tp or "planned",
        tr or ("shared" if tp else "planned"),
        test or "planned",
        tol,
        status,
    ]


PAPER_ROWS: list[list[str]] = [
    # ---- Preparation ----
    p(
        1,
        "Prep",
        "A1",
        "assumption",
        "Eliminations modeled only on regular single-elimination weeks; alive set A_s,t correctly identified",
        "",
        "",
        PRE,
        status="implemented",
    ),
    p(
        2,
        "Prep",
        "A2",
        "assumption",
        "Judge scores treated as relative performance ranking, rescaled comparable across weeks/seasons",
        "",
        "",
        PRE,
        status="implemented",
    ),
    p(
        3,
        "Prep",
        "A3",
        "assumption",
        "Weekly fan voting is a vote-share vector p; expected pattern q via softmax",
        "",
        "",
        P1,
        status="implemented",
    ),
    p(
        4,
        "Prep",
        "A4",
        "assumption",
        "Elimination probabilistic; worse combined signal more likely; temperature governs randomness",
        "",
        "",
        P1,
        status="implemented",
    ),
    p(
        5,
        "Prep",
        "A5",
        "assumption",
        "Weekly fan shares vary around trend q via Dirichlet centered at q",
        "",
        "",
        P1,
        status="implemented",
    ),
    p(
        6,
        "Prep",
        "A6",
        "assumption",
        "Counterfactual invariance: rule change does not change judge scores or fan preference",
        "",
        "",
        P2,
        status="implemented",
    ),
    p(
        7,
        "Prep",
        "A7",
        "assumption",
        "Within-season judging standard stable enough that judge-signal changes track real improvement",
        "",
        "",
        P3,
        status="implemented",
    ),
    p(
        8,
        "Prep",
        "A8",
        "assumption",
        "Fan support comparable across seasons at matched checkpoints, not across weeks within a season",
        "",
        "",
        P3,
        status="implemented",
    ),
    p(
        9,
        "Prep",
        "A9",
        "assumption",
        "Bottom-2 judges save: judges eliminate technically weaker of the bottom two",
        "",
        "",
        P2,
        status="implemented",
    ),
    p(
        10,
        "Prep",
        "notations",
        "table",
        "Notations table: core symbols (s,t,i,A,J,p,q,kappa,S,tau,i*,PCP,e_hat,Bottom2)",
        "docs/METHOD_SPEC.md#shared-notation",
        "docs/METHOD_SPEC.md#shared-notation",
        SHARED,
        status="implemented",
    ),
    p(
        11,
        "Prep",
        "preprocess-1",
        "formula",
        "Structural-zero handling: post-elimination zeros recoded NaN; original N/A preserved",
        "",
        "../src/0data_cleaning.ipynb; ../review/srcs_0/dwts_preprocess.py",
        PRE,
        status="implemented",
    ),
    p(
        12,
        "Prep",
        "preprocess-2",
        "formula",
        "Outcome parsing: elim_week_result, is_withdrew, is_place; withdrawals excluded",
        "",
        "../src/0data_cleaning.ipynb",
        PRE,
        status="implemented",
    ),
    p(
        13,
        "Prep",
        "preprocess-3",
        "formula",
        "Season length and activity window (active_until) -> weekly alive set",
        "",
        "../src/0data_cleaning.ipynb",
        PRE,
        status="implemented",
    ),
    p(
        14,
        "Prep",
        "preprocess-4",
        "formula",
        "Analysis tables: long judge, weekly panel, judge_rank/judge_percent, roster, elim events",
        "",
        "../src/build_event_table.py; ../review/srcs_0/dwts_preprocess.py",
        PRE,
        status="implemented",
    ),
    p(
        15,
        "Prep",
        "preprocess-5",
        "formula",
        "Cross-season rank normalization Z^J = Phi^-1(clip(1-(R^J-0.5)/N, 0.001, 0.999)) (Problem 3 only)",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    # ---- Problem 1 ----
    p(
        16,
        "Problem 1",
        "eq:J_pct",
        "formula",
        "Percentage-era judge signal J = T_i / sum_k T_k",
        "",
        "../src/model.py",
        P1,
        status="implemented",
    ),
    p(
        17,
        "Problem 1",
        "eq:J_rank",
        "formula",
        "Rank-era judge signal J = exp(-R_i) / sum_k exp(-R_k)",
        "",
        "../src/model.py",
        P1,
        status="implemented",
    ),
    p(
        18,
        "Problem 1",
        "eq:latent_score",
        "formula",
        "Latent popularity eta = x^T beta + u, u ~ N(0, sigma_u^2); x = {J, age}",
        "",
        "../src/model_new.py",
        P1,
        status="implemented",
    ),
    p(
        19,
        "Problem 1",
        "eq:prior_mean",
        "formula",
        "Expected fan share q = softmax(eta) = exp(eta)/sum exp(eta)",
        "",
        "../src/model.py",
        P1,
        status="implemented",
    ),
    p(
        20,
        "Problem 1",
        "eq:combined",
        "formula",
        "Combined score C = J + q",
        "",
        "../src/model.py",
        P1,
        status="implemented",
    ),
    p(
        21,
        "Problem 1",
        "eq:softmin",
        "formula",
        "Softmin elimination likelihood Pr(i* elim) = exp(-C_i*/tau)/sum exp(-C_k/tau)",
        "",
        "../src/model.py",
        P1,
        "problem1.model (R: integrated marginal)",
        status="implemented",
    ),
    p(
        22,
        "Problem 1",
        "eq:nll",
        "formula",
        "Penalized NLL L = sum [C_i*/tau + log sum exp(-C_k/tau)] + l_beta||beta||^2 + l_u||u||^2",
        "",
        "../src/model.py",
        P1,
        status="implemented",
    ),
    p(
        23,
        "Problem 1",
        "eq:posterior",
        "formula",
        "Dirichlet posterior pi(p|i*) propto (prod p_i^{kappa q_i - 1}) * softmin evidence",
        "",
        "../src/posterior_uncertainty.py",
        P1,
        "problem1.model (R)",
        status="implemented",
    ),
    p(
        24,
        "Problem 1",
        "is",
        "formula",
        "Importance sampling: draw p^b ~ Dirichlet(kappa q), reweight by softmin, weighted posterior",
        "",
        "../src/posterior_uncertainty.py",
        P1,
        "problem1.model (R)",
        status="implemented",
    ),
    p(
        25,
        "Problem 1",
        "week_trajectory.jpg",
        "figure",
        "Posterior fan-support trajectories (Season 8) heatmap",
        "visual",
        "../src/plot_uncertainty.py",
        P1,
        status="implemented",
    ),
    p(
        26,
        "Problem 1",
        "eq:top1",
        "metric",
        "Top-1 accuracy A = 1/N sum 1{argmin C_hat = i*}",
        "",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        27,
        "Problem 1",
        "acc_xgb",
        "metric",
        "XGBoost baseline top-1 accuracy (paper 0.806554; legacy run gives week-mean 0.821101 / season-mean 0.817496, D-20260901-11)",
        "0.806554",
        "../src/xgb_baseline.py",
        P1E,
        status="implemented",
    ),
    p(
        28,
        "Problem 1",
        "acc_torch",
        "metric",
        "torch_model top-1 accuracy (wins every season)",
        "0.952092",
        "../src/model.py; ../src/model_new.py",
        P1E,
        status="implemented",
    ),
    p(
        29,
        "Problem 1",
        "1_model_accuracy_line.png",
        "figure",
        "In-season accuracy by season (torch vs xgboost)",
        "visual",
        "../src/plot_cv_accuracy_line.py",
        P1E,
        status="implemented",
    ),
    p(
        30,
        "Problem 1",
        "eq:cum_consistency",
        "metric",
        "Cumulative consistency S_s = (1/H_K) sum_k (1/k)(n'_s,k / n_s,k)",
        "",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        31,
        "Problem 1",
        "cum_S",
        "metric",
        "Season-averaged cumulative consistency",
        "0.78",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        32,
        "Problem 1",
        "eq:pcp",
        "metric",
        "PCP = 1/B sum 1{argmin(J+p^b) = i*}",
        "",
        "../src/posterior_uncertainty.py",
        P1E,
        status="implemented",
    ),
    p(
        33,
        "Problem 1",
        "pcp_vs_alive.jpg",
        "figure",
        "Crowded-field effect: PCP rises as alive set shrinks",
        "visual",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        34,
        "Problem 1",
        "eq:ranking_gap",
        "metric",
        "Ranking gap Delta R = Rank_final - Rank_judge",
        "",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        35,
        "Problem 1",
        "ranking_gap.jpg",
        "figure",
        "Popularity premium: inferred fan rank vs ranking gap (paper claims R^2>0.6; reproduced R^2=0.2704, n=421, D-20260901-12)",
        "R^2>0.6",
        "../src/eval_metrics_viz.py",
        P1E,
        status="implemented",
    ),
    p(
        36,
        "Problem 1",
        "eq:ci",
        "metric",
        "90% credible interval CI90 = [Q_0.05, Q_0.95]; relative width RW = (hi-lo)/(p_hat+eps)",
        "",
        "../src/posterior_uncertainty.py",
        P1E,
        status="implemented",
    ),
    p(
        37,
        "Problem 1",
        "1_fig2_ci_heatmap_S21.png",
        "figure",
        "Season 21 relative CI width heatmap (heterogeneous uncertainty)",
        "visual",
        "../src/plot_uncertainty.py",
        P1E,
        status="implemented",
    ),
    p(
        38,
        "Problem 1",
        "ess",
        "method",
        "ESS diagnostic per week; flag low-ESS, increase B to stabilize",
        "",
        "../src/posterior_uncertainty.py",
        P1E,
        status="implemented",
    ),
    # ---- Problem 2 ----
    p(
        39,
        "Problem 2",
        "eq:rank_rule",
        "formula",
        "Rank rule: e_hat = argmax_i (rank(-T_i) + rank(-p_hat_i))",
        "",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        40,
        "Problem 2",
        "eq:pct_rule",
        "formula",
        "Percentage rule: e_hat = argmin_i (T_i/sum T + p_hat_i)",
        "",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        41,
        "Problem 2",
        "eq:dr",
        "metric",
        "Disagreement rate DR_s = 1/|W| sum 1{e_rank != e_pct}",
        "DR_s>0.6 frequent",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        42,
        "Problem 2",
        "2_posterior_probability.png",
        "figure",
        "Posterior agreement (bimodal)",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        43,
        "Problem 2",
        "2_weekly_disagreement.png",
        "figure",
        "Weekly disagreement",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        44,
        "Problem 2",
        "eq:override",
        "metric",
        "Override rate = 1/|W| sum 1{e_hat != argmin T}; FanWorst = 1{e = argmin p_hat}",
        "",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        45,
        "Problem 2",
        "2_posterior_delta.png",
        "figure",
        "Delta_s = E[Override_rank - Override_pct] < 0 (pct more fan override)",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        46,
        "Problem 2",
        "2_threshold_fan_share.png",
        "figure",
        "Threshold fan share for judge-worst to survive",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        47,
        "Problem 2",
        "eq:bottom2",
        "formula",
        "Bottom-2 + save: B = arg two-min S, e_hat = argmin_{i in B} J_i",
        "",
        "../src/b2_save_metrics.py",
        P2,
        status="implemented",
    ),
    p(
        48,
        "Problem 2",
        "eq:rev_rate",
        "metric",
        "Reversal rate rev_rate = Pr(e_B2 != e_direct)",
        "",
        "../src/b2_save_metrics.py",
        P2,
        status="implemented",
    ),
    p(
        49,
        "Problem 2",
        "3_Reversal_Heatmap_Rank.png",
        "figure",
        "Reversal heatmap (rank)",
        "visual",
        "../src/b2_save_metrics.py",
        P2,
        status="implemented",
    ),
    p(
        50,
        "Problem 2",
        "3_Reversal_Heatmap_Percent.png",
        "figure",
        "Reversal heatmap (percentage)",
        "visual",
        "../src/b2_save_metrics.py",
        P2,
        status="implemented",
    ),
    p(
        51,
        "Problem 2",
        "3_Discrepancy_Scatter.png",
        "figure",
        "Judge-fan disagreement landscape (top-left quadrant controversies)",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2C,
        status="implemented",
    ),
    p(
        52,
        "Problem 2",
        "tab:selected_cases",
        "table",
        "Selected controversy cases (|d|, Flip): Jerry Rice 3.69/0.87; B.R.Cyrus 3.25/0.75; B.Palin 4.30/0.97; Bobby Bones 4.00/0.57; Tinashe 8.50/0.57; Vinny G. 9.88/0.33",
        "see description",
        "../src/sim_rank_trend_cases.py",
        P2C,
        status="implemented",
    ),
    p(
        53,
        "Problem 2",
        "4_EliminationProbability_*.png",
        "figure",
        "Six-case elimination probability panels",
        "visual",
        "../src/sim_rank_trend_cases.py",
        P2C,
        status="implemented",
    ),
    p(
        54,
        "Problem 2",
        "4_SurvivalCurves_*.png",
        "figure",
        "Six-case survival curves (Save vs Direct)",
        "visual",
        "../src/sim_rank_trend_cases.py",
        P2C,
        status="implemented",
    ),
    p(
        55,
        "Problem 2",
        "4_RankVsPercentage_*.png",
        "figure",
        "Six-case rank divergence panels",
        "visual",
        "../src/sim_rank_trend_cases.py",
        P2C,
        status="implemented",
    ),
    p(
        56,
        "Problem 2",
        "5_Mechanism phase diagram.png",
        "figure",
        "Mechanism phase diagram (fan influence x, judge consistency y)",
        "visual",
        "../src/2_rank_vs_pct_cross_season.ipynb",
        P2,
        status="implemented",
    ),
    p(
        57,
        "Problem 2",
        "recommendation",
        "claim",
        "Recommendation: Percentage base + Bottom-2 judges save",
        "",
        "",
        P2,
        status="implemented",
    ),
    # ---- Problem 3 ----
    p(
        58,
        "Problem 3",
        "eq:demo_model",
        "formula",
        "Demographic OLS: Y = alpha + beta_Age Age + sum delta_k I(industry=k)",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        59,
        "Problem 3",
        "coef_age",
        "metric",
        "Judge age penalty beta_Age ~ -0.04 (all weeks); fan age penalty reverses by W11",
        "-0.04",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        60,
        "Problem 3",
        "coef_actor",
        "metric",
        "Actor: judge W1 beta~0.16; fan W6 beta=-0.87 (audience fatigue)",
        "0.16 / -0.87",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        61,
        "Problem 3",
        "6_Success_Factors_Judges_vs_Fans.png",
        "figure",
        "Temporal evolution of judge/fan coefficient heatmap",
        "visual",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        62,
        "Problem 3",
        "eq:partner",
        "formula",
        "Partner traits H_abil = avg rank_past; H_exp = sum I(s in S_p)",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        63,
        "Problem 3",
        "eq:fe_model",
        "formula",
        "Fixed effects: Z = mu + g1 H_abil + g2 H_exp + alpha_p + eps",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        64,
        "Problem 3",
        "coef_tenure",
        "metric",
        "Partner tenure correlates with judge scores r=0.23, near-zero with fan votes",
        "0.23",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        65,
        "Problem 3",
        "6_Partner_Traits_Correlation.png",
        "figure",
        "Partner trait correlation heatmap",
        "visual",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        66,
        "Problem 3",
        "6_Pro_Partner_Historical_Impact.png",
        "figure",
        "Partner heterogeneity (raw ability vs fixed effects)",
        "visual",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        67,
        "Problem 3",
        "eq:surprise",
        "formula",
        "Surprise S = Z_Judge,t - Z_Fan,t-1; Growth G = Z_Fan,t - Z_Fan,t-1",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        68,
        "Problem 3",
        "eq:growth_model",
        "formula",
        "Quadratic interaction G = b0 + b1 S + b2 S^2 + b3 (S x H_exp)",
        "",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        69,
        "Problem 3",
        "coef_surprise",
        "metric",
        "Surprise linear beta1=0.34 (p<0.001); beta2>0 (Matthew); beta3>0 (leverage)",
        "0.34",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        70,
        "Problem 3",
        "6_Surprise_Effect_Vote_Growth.png",
        "figure",
        "Surprise -> vote growth linear response",
        "visual",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    p(
        71,
        "Problem 3",
        "6_Surprise_NonLinearity_and_Interaction.png",
        "figure",
        "Surprise nonlinearity + tenure interaction",
        "visual",
        "../src/dwts_pro_celeb_regression.py",
        P3,
        status="implemented",
    ),
    # ---- Problem 4 ----
    p(
        72,
        "Problem 4",
        "eq:shock",
        "metric",
        "Technical shock rate Shock_k = Pr(elim in top-k judges)",
        "",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        73,
        "Problem 4",
        "eq:v1_gate",
        "formula",
        "V1: judge bottom-K gate B^J = arg K-min J; fans eliminate argmin p in B^J (K=3)",
        "K=3",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        74,
        "Problem 4",
        "v1_split",
        "hyperparameter",
        "V1 early/late split threshold m=8",
        "m=8",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        75,
        "Problem 4",
        "eq:v2_temper",
        "formula",
        "V2 fan tempering p~ = p^gamma / sum p^gamma (0<gamma<=1)",
        "",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        76,
        "Problem 4",
        "eq:v2_judge",
        "formula",
        "V2 judge sharpening J~ = J^delta / sum J^delta (delta>=1)",
        "",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        77,
        "Problem 4",
        "eq:momentum",
        "formula",
        "Momentum m = T - (1/L)sum T_{t-l}; B = mu tanh(z/c)",
        "",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        78,
        "Problem 4",
        "eq:v2_score",
        "formula",
        "V2 score S = w_J J~ + w_F p~ + B; Bottom-2 then judges save",
        "",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        79,
        "Problem 4",
        "v2_params",
        "hyperparameter",
        "V2 defaults w_J=0.80 w_F=0.20 gamma=0.45 delta=1.35 mu=0.01 L in {2,3}",
        "w_J=.80 w_F=.20 g=.45 d=1.35 mu=.01",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        80,
        "Problem 4",
        "8_V1_plot1.png",
        "figure",
        "V1 delta average rank (S3-S1) heatmap",
        "visual",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        81,
        "Problem 4",
        "8_fig_diff_contour_avg_rank_S3_minus_S1.png",
        "figure",
        "Archetype cumulative survival by scheme (V1)",
        "visual",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        82,
        "Problem 4",
        "8_fig_ribbon_survival_by_archetype.png",
        "figure",
        "V0 vs V2 archetype survival ribbon",
        "visual",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        83,
        "Problem 4",
        "8_fig_sim2_trend_2_Jerry_Rice.png; 8_fig_sim2_trend_4_Billy_Ray_Cyrus.png; 8_fig_sim2_trend_11_Bristol_Palin.png; 8_fig_sim2_trend_27_Bobby_Bones.png; 8_fig_sim2_trend_27_Tinashe.png; 8_fig_sim2_trend_31_Vinny_Guadagnino.png",
        "figure",
        "Six-case simulated weekly rank (V0 vs V2)",
        "visual",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        84,
        "Problem 4",
        "v1_immunity",
        "claim",
        "V1 gives popular contestants pre-filter immunity (does not correct canonical cases)",
        "",
        "../src/season_simulator.py",
        P4,
        status="implemented",
    ),
    p(
        85,
        "Problem 4",
        "v2_bones",
        "claim",
        "V2: Bobby Bones champion -> 6th; Tinashe protected W7->W8",
        "Bones->6th",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
    p(
        86,
        "Problem 4",
        "recommendation",
        "claim",
        "Recommendation: V2 for legitimacy, V1 for engagement, V1-early/V2-late hybrid",
        "",
        "",
        P4,
        status="implemented",
    ),
    # ---- Sensitivity ----
    p(
        87,
        "Sensitivity",
        "A1",
        "method",
        "Perturb hyperparameters (tau, kappa)",
        "",
        "../src/sensitivity_analysis_a.py",
        SEN,
        status="implemented",
    ),
    p(
        88,
        "Sensitivity",
        "A2",
        "method",
        "Perturb regularization balance lambda_u/lambda_beta",
        "",
        "../src/sensitivity_analysis_a.py",
        SEN,
        status="implemented",
    ),
    p(
        89,
        "Sensitivity",
        "A3",
        "method",
        "Alternative judge-to-share transforms",
        "",
        "../src/sensitivity_analysis_a.py",
        SEN,
        status="implemented",
    ),
    p(
        90,
        "Sensitivity",
        "A4",
        "method",
        "Leave-one-season-out refits",
        "",
        "../src/sensitivity_analysis_a.py",
        SEN,
        status="implemented",
    ),
    p(
        91,
        "Sensitivity",
        "10_stability_scatter.png",
        "figure",
        "Stability of inferred fan support (Spearman)",
        "visual",
        "../src/sensitivity_viz_a.py",
        SEN,
        status="implemented",
    ),
    p(
        92,
        "Sensitivity",
        "10_tornado_pcp_mean.png",
        "figure",
        "PCP sensitivity tornado (tau dominates, then kappa)",
        "visual",
        "../src/sensitivity_viz_a.py",
        SEN,
        status="implemented",
    ),
    p(
        93,
        "Sensitivity",
        "10_A1_line_pcp_mean_by_kappa.png",
        "figure",
        "PCP_mean monotonic in tau, kappa shifts upward",
        "visual",
        "../src/sensitivity_viz_a.py",
        SEN,
        status="implemented",
    ),
    # ---- Model analysis + memo ----
    p(
        94,
        "Analysis",
        "strength",
        "claim",
        "Strength: uncertainty-aware inference; end-to-end testable pipeline",
        "",
        "",
        SHARED,
        status="implemented",
    ),
    p(
        95,
        "Analysis",
        "weakness",
        "claim",
        "Weakness: limited identifiability; V2 attribution confounded (needs ablation)",
        "",
        "",
        P4,
        status="implemented",
    ),
    p(
        96,
        "Memo",
        "memo_claims",
        "claim",
        "Memo: Actor's curse beta~-0.87; Bones->6th; Tinashe +30% survival",
        "beta~-0.87",
        "../src/season_simulator2.py",
        P4,
        status="implemented",
    ),
]

REVIEW_HEADER = [
    "id",
    "source",
    "loc",
    "item_type",
    "requirement",
    "target_value",
    "legacy_producer",
    "track_P_module",
    "track_R_module",
    "acceptance_test",
    "tolerance",
    "status",
]


def r(
    idx: int,
    source: str,
    loc: str,
    item_type: str,
    requirement: str,
    target_value: str = "",
    producer: str = "",
    tp: str = "",
    tr: str = "",
    test: str = "",
    tol: str = "",
    status: str = "planned",
) -> list[str]:
    return [
        f"R-{idx:03d}",
        source,
        loc,
        item_type,
        requirement,
        target_value,
        producer,
        tp or "planned",
        tr or ("shared" if tp else "planned"),
        test or "planned",
        tol,
        status,
    ]


REVIEW_ROWS: list[list[str]] = [
    # Preprocessing validation targets (00_codex_preprocessing_refactor_prompt.md)
    r(
        1,
        "refactor_preprocess",
        "shape_raw",
        "validation",
        "raw shape (421, 53)",
        "421 x 53",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        2,
        "refactor_preprocess",
        "score_cols",
        "validation",
        "44 judge score columns",
        "44",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        3,
        "refactor_preprocess",
        "max_week",
        "validation",
        "max week in columns = 11",
        "11",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        4,
        "refactor_preprocess",
        "n_seasons",
        "validation",
        "34 seasons (1..34)",
        "34",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        5,
        "refactor_preprocess",
        "zeros_raw",
        "validation",
        "raw literal zeros = 4671",
        "4671",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        6,
        "refactor_preprocess",
        "missing_raw",
        "validation",
        "raw missing scores = 4741",
        "4741",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        7,
        "refactor_preprocess",
        "clean_missing",
        "validation",
        "clean missing scores = 9412 (zeros -> NaN, N/A preserved)",
        "9412",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        8,
        "refactor_preprocess",
        "shape_clean",
        "validation",
        "df_clean shape (421, ~60)",
        "421 x ~60",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        9,
        "refactor_preprocess",
        "shape_long",
        "validation",
        "df_long_judge shape (18524, ~21)",
        "18524 x ~21",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        10,
        "refactor_preprocess",
        "shape_weekly",
        "validation",
        "df_weekly shape (4199, ~23)",
        "4199 x ~23",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        11,
        "refactor_preprocess",
        "shape_roster",
        "validation",
        "df_roster shape (4199, ~7)",
        "4199 x ~7",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        12,
        "refactor_preprocess",
        "shape_elim",
        "validation",
        "df_elim_events shape (292, ~5)",
        "292 x ~5",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        13,
        "refactor_preprocess",
        "withdrawn",
        "validation",
        "withdrawn contestants = 10",
        "10",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        14,
        "refactor_preprocess",
        "final_place",
        "validation",
        "final-placement rows = 113",
        "113",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        15,
        "refactor_preprocess",
        "performed",
        "validation",
        "performed weekly rows = 2777",
        "2777",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        16,
        "refactor_preprocess",
        "eligible",
        "validation",
        "eligible weekly rows = 2780",
        "2780",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        17,
        "refactor_preprocess",
        "final_events",
        "validation",
        "final events = 34",
        "34",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        18,
        "refactor_preprocess",
        "nonfinal_events",
        "validation",
        "non-final events = 258",
        "258",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        19,
        "refactor_preprocess",
        "m_elim",
        "validation",
        "non-final m_elim distribution {1:218, 2:37, 3:3}",
        "{1:218, 2:37, 3:3}",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        20,
        "refactor_preprocess",
        "era_official",
        "requirement",
        "Official era mapping: 1-2 rank, 3-27 percent, 28-34 rank (Bottom-2 ~28+)",
        "1-2 rank; 3-27 pct; 28-34 rank",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
        PRE,
    ),
    r(
        21,
        "refactor_preprocess",
        "era_legacy",
        "requirement",
        "Legacy era mapping suspected reversed (season>=28 -> percent); audit before reuse",
        "suspected",
        "../src/model.py",
        PRE,
        PRE,
    ),
    # Problem 1 spec (01_codex_problem1_refactor_prompt.md)
    r(
        22,
        "refactor_problem1",
        "panel_cols",
        "requirement",
        "Problem 1 panel columns (alive, elim_this_week_end, is_final_week, j_metric, era, ...)",
        "",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1,
    ),
    r(
        23,
        "refactor_problem1",
        "train_weeks",
        "validation",
        "training weeks ~218 single-elimination non-final weeks",
        "218",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1,
    ),
    r(
        24,
        "refactor_problem1",
        "features",
        "requirement",
        "Features j_metric_z, age_z, era_is_percent + contestant-season intercept",
        "",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1,
    ),
    r(
        25,
        "refactor_problem1",
        "hyperparams",
        "hyperparameter",
        "tau_train=0.05 tau_like=0.15 kappa=10 l2_beta=l2_u=0.05 lr=0.02 steps=600 bs=32 B=1200 seed=42",
        "see description",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1,
    ),
    r(
        26,
        "refactor_problem1",
        "posterior_metrics",
        "requirement",
        "Posterior outputs p_mean, ci_lo_05, ci_hi_95, ci_width, ci_rel_width, ess, ess_ratio, pcp, has_posterior",
        "",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1,
    ),
    r(
        27,
        "refactor_problem1",
        "eval",
        "requirement",
        "Evaluation: top-1, season accuracy, PCP vs alive_n, RW, ESS",
        "",
        "../review/problem1_rebuild/problem1_fan_support.py",
        P1E,
    ),
    r(
        28,
        "refactor_problem1",
        "top1_rebuild",
        "metric",
        "Review rebuild overall top-1 accuracy",
        "0.949541",
        "../review/problem1_rebuild/outputs/problem1_summary.json",
        P1E,
    ),
    r(
        29,
        "refactor_problem1",
        "overclaim",
        "requirement",
        "Do not claim p_mean is true fan vote; it is a posterior estimate",
        "",
        "",
        P1,
    ),
    # Track R correction (review_all.md)
    r(
        30,
        "review_all",
        "track_r_marginal",
        "formula",
        "Track R: P(Y|beta,u) = integral P(Y|p,J) Dirichlet(p|kappa q) dp (avoid double use)",
        "",
        "",
        P1,
        P1,
    ),
    r(
        31,
        "review_all",
        "alive_set",
        "formula",
        "Alive set A_s,t = {i: eligible}; eligible = 1{t<=H_i,s} 1{t<=T_s}",
        "",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        32,
        "review_all",
        "season_len",
        "formula",
        "Season length T_s = max{w: exists i, sum_j X_{i,s,w,j} > 0}",
        "",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        33,
        "review_all",
        "horizon",
        "formula",
        "Active horizon H_i,s (elim week / season len / last positive week for withdrew)",
        "",
        "../review/srcs_0/dwts_preprocess.py",
        PRE,
    ),
    r(
        34,
        "review_all",
        "judge_signal",
        "formula",
        "Judge signal J: percentage = T/sum T; rank = exp(-R)/sum exp(-R)",
        "",
        "../src/model.py",
        P1,
    ),
    r(
        35,
        "review_all",
        "montecarlo_error",
        "requirement",
        "Track R reports MC error, ESS, convergence, seed/sample-count sensitivity",
        "",
        "",
        P1,
        P1,
    ),
    # Review Problem 2 mechanism evaluation (review_all.md, section "评估不同的票数合并机制...")
    r(
        36,
        "review_all",
        "override_rate",
        "formula",
        "Override_s^m = 1/|W_s| sum_t I(e^m != e_J); Percentage-based rule overrides the judge more often",
        "",
        "src/dwts_reproduction/problem2/replay.py",
        P2,
        P2,
        "test_problem2_replay",
        "",
        "implemented",
    ),
    r(
        37,
        "review_all",
        "bottom2_reversal",
        "formula",
        "Reversal rev = P(Bottom2+Save != Direct elimination); percentage reversal higher and rises as the alive set shrinks",
        "",
        "src/dwts_reproduction/problem2/replay.py",
        P2,
        P2,
        "test_problem2_replay",
        "",
        "implemented",
    ),
    r(
        38,
        "review_all",
        "controversy_scatter",
        "visual",
        "Controversy-group scatter: x = fan rank - judge rank, y = fan share - judge share; second-quadrant contestants (fan-loved, judge-scored low) most exposed to Bottom-2",
        "",
        "src/dwts_reproduction/problem2/replay.py",
        P2,
        P2,
        "test_problem2_replay",
        "",
        "implemented",
    ),
    r(
        39,
        "review_all",
        "phase_axes",
        "formula",
        "Phase axes: x = mu(|p_i - J_i|) fan influence, y = 1 - mu(|r_Final - r_J|) judge consistency (r_Final = descending rank of survival-week counts, r_J = descending rank of mean judge_percent)",
        "",
        "src/dwts_reproduction/problem2/mechanism_phase.py",
        P2,
        P2,
        "test_mechanism_phase",
        "",
        "implemented",
    ),
    r(
        40,
        "review_all",
        "perc_bottom2_claim",
        "claim",
        "Review claim: Perc+Bottom2 has the highest overall x and y among the four mechanisms",
        "reproduced data: rank_bottom2 highest on both axes; claim not supported (recorded honestly)",
        "src/dwts_reproduction/problem2/mechanism_phase.py",
        P2,
        P2,
        "test_mechanism_phase",
        "",
        "implemented",
    ),
]

# --- Phase 7: every review requirement is implemented and tested --------------------
# R-001..R-035 were authored as *planned* Phase 0 targets; by Phase 7 each maps to an
# implemented, tested module. Record the validating test for every row that does not yet
# carry an explicit one, and flip its status to ``implemented``.
R_STATUS: dict[int, str] = {
    # Preprocessing validation targets -> src/dwts_reproduction/preprocess.py
    **dict.fromkeys(range(1, 22), "test_preprocess"),
    # Problem 1 panel / model / evaluation -> problem1 modules
    22: "test_problem1_panel",
    23: "test_problem1_panel",
    24: "test_problem1_panel",
    25: "test_problem1_track_p",
    26: "test_problem1_track_p",
    27: "test_problem1_evaluate",
    28: "test_problem1_evaluate",
    29: "test_top1_metrics_are_in_sample_and_labeled",  # overclaim guard
    # Track R corrections -> problem1.track_r
    30: "test_problem1_track_r",
    31: "test_preprocess",
    32: "test_preprocess",
    33: "test_preprocess",
    34: "test_problem1_panel",
    35: "test_problem1_track_r",
}
for _row in REVIEW_ROWS:
    _idx = int(_row[0].split("-")[1])
    if _idx in R_STATUS:
        _row[9] = R_STATUS[_idx]  # acceptance_test column
        _row[11] = "implemented"  # status column


def _write_csv(header: list[str], rows: list[list[str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(header)
        writer.writerows(rows)


def _write_markdown(
    title: str,
    header: list[str],
    rows: list[list[str]],
    group_col: int,
    path: Path,
) -> None:
    lines = [f"# {title}", ""]
    lines.append(
        "> Canonical data: `manifests/` CSV. Generated by `scripts/build_traceability.py`."
    )
    lines.append("> `track_P_module` / `track_R_module` / `acceptance_test` are *planned* targets;")
    lines.append("> `status=planned` means mapped but not yet implemented in Phase 0.")
    lines.append("")
    lines.append(f"| {' | '.join(header)} |")
    lines.append(f"|{'|'.join(['---'] * len(header))}|")
    for row in rows:
        lines.append("| " + " | ".join(_esc(cell) for cell in row) + " |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _esc(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def main() -> int:
    paths = load_paths()
    _write_csv(PAPER_HEADER, PAPER_ROWS, paths.manifest_dir / "traceability_paper.csv")
    _write_csv(REVIEW_HEADER, REVIEW_ROWS, paths.manifest_dir / "traceability_review.csv")
    _write_markdown(
        "Paper traceability inventory (Track P)",
        PAPER_HEADER,
        PAPER_ROWS,
        1,
        paths.repo_root / "docs" / "TRACEABILITY_PAPER.md",
    )
    _write_markdown(
        "Review traceability inventory (Track R)",
        REVIEW_HEADER,
        REVIEW_ROWS,
        1,
        paths.repo_root / "docs" / "TRACEABILITY_REVIEW.md",
    )
    print(f"paper rows: {len(PAPER_ROWS)}")
    print(f"review rows: {len(REVIEW_ROWS)}")
    print("wrote manifests/traceability_{paper,review}.csv and docs/TRACEABILITY_{PAPER,REVIEW}.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
