#!/usr/bin/env python3
"""Generate the legacy asset inventory.

Walks the read-only sources, classifies each file by artifact role, and writes:

- ``docs/LEGACY_INVENTORY.md`` — human-readable counts per role, the ``src/`` breakdown
  (source vs. cache), and the per-role file list.
- ``manifests/legacy_inventory.csv`` — machine-readable ``role,relative_path,sha256,size_bytes``.

Counts are computed programmatically so no hand-counted claim is authoritative.
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(_SRC))

from dwts_reproduction.config import load_paths  # noqa: E402
from dwts_reproduction.hashing import build_manifest  # noqa: E402

ROLE_LABELS = {
    "raw_input": "Raw authoritative inputs",
    "paper_spec": "Paper specification (Track P)",
    "review_spec": "Review specification (Track R)",
    "legacy_impl": "Legacy implementation evidence",
    "legacy_output": "Derived legacy outputs / baselines",
    "reference": "Reference artifacts (provenance TBD)",
}


def _src_breakdown(src_dir: Path) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for file_path in src_dir.rglob("*"):
        if not file_path.is_file() or file_path.name == ".DS_Store":
            continue
        # Skip interpreter caches and virtual environments so the inventory is
        # deterministic regardless of what has been imported or installed locally
        # (mirrors the pruning in ``hashing._is_excluded``).
        if "__pycache__" in file_path.parts or ".venv" in file_path.parts:
            continue
        if file_path.suffix == ".py":
            counts["py"] += 1
        elif file_path.suffix == ".ipynb":
            counts["ipynb"] += 1
        elif file_path.suffix == ".pyc":
            counts["pyc"] += 1
        else:
            counts["other"] += 1
    return dict(counts)


def _render_markdown(
    rows: list[tuple[str, str, str]], skipped: list[str], src_counts: dict[str, int]
) -> str:
    by_role: Counter[str] = Counter(role for role, _, _ in rows)

    lines: list[str] = []
    lines.append("# Legacy asset inventory")
    lines.append("")
    lines.append("> Generated by `scripts/inventory_sources.py`. Do not hand-edit; counts are")
    lines.append("> recomputed from the read-only sources on every run.")
    lines.append("")
    lines.append("## Summary by artifact role")
    lines.append("")
    lines.append("| role | count | meaning |")
    lines.append("|---|---|---|")
    for role in sorted(ROLE_LABELS):
        lines.append(f"| `{role}` | {by_role.get(role, 0)} | {ROLE_LABELS[role]} |")
    lines.append(
        f"| *(excluded)* | {len(skipped)} | caches / build artifacts / non-authoritative |"
    )
    lines.append("")
    lines.append("## `src/` breakdown")
    lines.append("")
    lines.append("| kind | count |")
    lines.append("|---|---|")
    lines.append(f"| `.py` sources | {src_counts.get('py', 0)} |")
    lines.append(f"| `.ipynb` notebooks | {src_counts.get('ipynb', 0)} |")
    lines.append(f"| `.pyc` compiled caches | {src_counts.get('pyc', 0)} |")
    lines.append(f"| other | {src_counts.get('other', 0)} |")
    lines.append("")
    lines.append("## Per-role files")
    lines.append("")
    for role in sorted(ROLE_LABELS):
        files = sorted(rel for r, _, rel in rows if r == role)
        lines.append(f"### {role} ({len(files)})")
        lines.append("")
        for rel in files:
            lines.append(f"- `{rel}`")
        lines.append("")
    if skipped:
        lines.append("## Excluded (not hashed)")
        lines.append("")
        for rel in skipped:
            lines.append(f"- `{rel}`")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    paths = load_paths()
    rows, skipped = build_manifest(paths.source_root)
    src_counts = _src_breakdown(paths.src_dir)

    # Machine-readable CSV with sizes.
    csv_path = paths.manifest_dir / "legacy_inventory.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["role", "relative_path", "sha256", "size_bytes"])
        for role, digest, rel in rows:
            size = (paths.source_root / rel).stat().st_size
            writer.writerow([role, rel, digest, size])

    md_path = paths.repo_root / "docs" / "LEGACY_INVENTORY.md"
    md_path.write_text(_render_markdown(rows, skipped, src_counts), encoding="utf-8")

    by_role = Counter(role for role, _, _ in rows)
    print(f"wrote {md_path} and {csv_path}")
    print(f"roles: {dict(sorted(by_role.items()))}")
    print(f"excluded: {len(skipped)}")
    print(f"src breakdown: {src_counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
