#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DWTS (MCM/ICM 2026 Problem C) — Regression analysis of:
- Pro dancer historical performance ("win rate" / prior mean placement_z)
- Celebrity characteristics (age, industry, home country)
on:
- final placement_z
- judge-score-derived z metrics at week 1/6/11
- fan-vote-estimate-derived z metrics at week 1/6/final

Data input: data_3.csv (one row per (season, celebrity) with engineered outcomes).
Author: generated by ChatGPT (reproducible script).
Python: 3.10+
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from scipy.stats import pearsonr
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error


# ----------------------------
# Configuration
# ----------------------------

OUTCOMES: Dict[str, str] = {
    "placement_z": "placement_z",
    "judge_w1": "week1_judge_score_placement_z",
    "judge_w6": "week6_judge_score_placement_z",
    "judge_w11": "week11_judge_score_placement_z",
    "fan_w1": "week1_p_score_placement_z",
    "fan_w6": "week6_p_score_placement_z",
    # NOTE: data_3.csv provides "week_final_p_score_placement_z" rather than week11 fan.
    # We interpret this as a late-stage fan-sentiment proxy (typically near the end of season).
    "fan_final": "week_final_p_score_placement_z",
}

KEY_NUMERIC = [
    "celebrity_age_during_season",
    "pro_hist_mean_placez",
    "pro_hist_win_rate",
    "pro_hist_top3_rate",
]


@dataclass
class OLSResult:
    outcome: str
    spec: str
    n: int
    r2: float
    adj_r2: float
    aic: float


# ----------------------------
# I/O
# ----------------------------

def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])
    # basic types
    df["season"] = df["season"].astype(int)
    df["placement"] = pd.to_numeric(df["placement"], errors="coerce")
    df["placement_z"] = pd.to_numeric(df["placement_z"], errors="coerce")
    df["celebrity_age_during_season"] = pd.to_numeric(df["celebrity_age_during_season"], errors="coerce")
    return df


# ----------------------------
# Feature engineering
# ----------------------------

def group_rare_categories(s: pd.Series, min_count: int = 6, other_label: str = "Other") -> pd.Series:
    """Keep categories appearing >= min_count; map rest to 'Other' (and fill NaN->Unknown)."""
    s2 = s.fillna("Unknown").astype(str)
    counts = s2.value_counts(dropna=False)
    keep = set(counts[counts >= min_count].index)
    return s2.where(s2.isin(keep), other_label)


def add_pro_history_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pro dancer history based on PRIOR seasons only (avoid leakage).

    For each pro dancer p and season s:
      - pro_hist_mean_placez(p,s): expanding mean of placement_z over seasons < s
      - pro_hist_win_rate(p,s): expanding mean of I(placement==1) over seasons < s
      - pro_hist_top3_rate(p,s): expanding mean of I(placement<=3) over seasons < s
      - pro_hist_n_prev(p,s): number of prior appearances (seasons < s)

    If no history exists, set to 0.
    """
    out = df.copy()

    out = out.sort_values(["ballroom_partner", "season", "celebrity_name"]).reset_index(drop=True)
    g = out.groupby("ballroom_partner", sort=False)

    out["pro_hist_n_prev"] = g.cumcount()

    out["pro_hist_mean_placez"] = g["placement_z"].apply(
        lambda s: s.shift(1).expanding().mean()
    ).reset_index(level=0, drop=True)

    out["pro_hist_win_rate"] = g["placement"].apply(
        lambda s: (s.shift(1).eq(1)).expanding().mean()
    ).reset_index(level=0, drop=True)

    out["pro_hist_top3_rate"] = g["placement"].apply(
        lambda s: (s.shift(1).le(3)).expanding().mean()
    ).reset_index(level=0, drop=True)

    for c in ["pro_hist_mean_placez", "pro_hist_win_rate", "pro_hist_top3_rate"]:
        out[c] = out[c].fillna(0.0)

    # restore canonical sort for reporting
    out = out.sort_values(["season", "placement", "celebrity_name"]).reset_index(drop=True)
    return out


def engineer_features(df: pd.DataFrame, min_cat_count: int = 6) -> pd.DataFrame:
    out = df.copy()

    # Celebrity categorical groups (as requested)
    out["industry_grp"] = group_rare_categories(out["celebrity_industry"], min_count=min_cat_count)
    out["country_grp"] = group_rare_categories(out["celebrity_homecountry_region"], min_count=min_cat_count)

    # Pro dancer history (leakage-safe)
    out = add_pro_history_features(out)

    return out


# ----------------------------
# Regression (OLS with robust SE)
# ----------------------------

def fit_ols(df: pd.DataFrame, y: str, rhs: str, robust: str = "HC3"):
    cols_needed = [
        y, "celebrity_age_during_season", "industry_grp", "country_grp", "season",
        "pro_hist_mean_placez", "pro_hist_win_rate", "pro_hist_top3_rate",
    ]
    d = df[cols_needed].copy()
    d = d.dropna(subset=[y, "celebrity_age_during_season"])
    model = smf.ols(f"{y} ~ {rhs}", data=d).fit(cov_type=robust)
    return model, len(d)


def fit_all_ols(df: pd.DataFrame) -> Tuple[pd.DataFrame, Dict[Tuple[str, str], object]]:
    base_rhs = (
        "celebrity_age_during_season + pro_hist_mean_placez + pro_hist_win_rate + pro_hist_top3_rate"
        " + C(industry_grp) + C(country_grp)"
    )
    fe_rhs = base_rhs + " + C(season)"

    rows: List[dict] = []
    fitted: Dict[Tuple[str, str], object] = {}

    for outcome, y in OUTCOMES.items():
        m_base, n_base = fit_ols(df, y, base_rhs)
        m_fe, n_fe = fit_ols(df, y, fe_rhs)

        fitted[(outcome, "base")] = m_base
        fitted[(outcome, "seasonFE")] = m_fe

        rows.append({"outcome": outcome, "spec": "base", "n": n_base, "R2": m_base.rsquared,
                     "adjR2": m_base.rsquared_adj, "AIC": m_base.aic})
        rows.append({"outcome": outcome, "spec": "seasonFE", "n": n_fe, "R2": m_fe.rsquared,
                     "adjR2": m_fe.rsquared_adj, "AIC": m_fe.aic})

    summary = pd.DataFrame(rows).sort_values(["outcome", "spec"]).reset_index(drop=True)
    return summary, fitted


def extract_key_coefs(fitted: Dict[Tuple[str, str], object], spec: str = "base") -> pd.DataFrame:
    rows = []
    for outcome, y in OUTCOMES.items():
        m = fitted.get((outcome, spec))
        if m is None:
            continue
        for term in ["celebrity_age_during_season", "pro_hist_mean_placez", "pro_hist_win_rate", "pro_hist_top3_rate"]:
            if term in m.params.index:
                rows.append({
                    "outcome": outcome,
                    "term": term,
                    "coef": float(m.params[term]),
                    "se": float(m.bse[term]),
                    "p": float(m.pvalues[term]),
                })
    return pd.DataFrame(rows).sort_values(["outcome", "term"]).reset_index(drop=True)


# ----------------------------
# Effect decomposition via ΔR2
# ----------------------------

def r2_for_formula(df: pd.DataFrame, y: str, rhs: str) -> Tuple[float, int]:
    d = df.dropna(subset=[y, "celebrity_age_during_season"]).copy()
    m = smf.ols(f"{y} ~ {rhs}", data=d).fit()
    return float(m.rsquared), int(len(d))


def incremental_r2_table(df: pd.DataFrame) -> pd.DataFrame:
    base_rhs = (
        "celebrity_age_during_season + pro_hist_mean_placez + pro_hist_win_rate + pro_hist_top3_rate"
        " + C(industry_grp) + C(country_grp)"
    )
    rhs_no_pro = "celebrity_age_during_season + C(industry_grp) + C(country_grp)"
    rhs_no_cat = "celebrity_age_during_season + pro_hist_mean_placez + pro_hist_win_rate + pro_hist_top3_rate"

    rows = []
    for outcome, y in OUTCOMES.items():
        r2_full, n = r2_for_formula(df, y, base_rhs)
        r2_no_pro, _ = r2_for_formula(df, y, rhs_no_pro)
        r2_no_cat, _ = r2_for_formula(df, y, rhs_no_cat)
        rows.append({
            "outcome": outcome,
            "n": n,
            "R2_full": r2_full,
            "ΔR2_pro_given_celeb": r2_full - r2_no_pro,
            "ΔR2_industry_country": r2_full - r2_no_cat,
        })
    return pd.DataFrame(rows).sort_values("outcome").reset_index(drop=True)


# ----------------------------
# Predictive check: forward (by season) CV Pearson r
# ----------------------------

def make_X(df: pd.DataFrame) -> pd.DataFrame:
    X = df[[
        "celebrity_age_during_season",
        "pro_hist_mean_placez",
        "pro_hist_win_rate",
        "pro_hist_top3_rate",
        "industry_grp",
        "country_grp",
    ]].copy()
    X = pd.get_dummies(X, columns=["industry_grp", "country_grp"], drop_first=True)
    return X


def season_forward_cv(df: pd.DataFrame, ycol: str, *, alpha: float = 1.0, min_train_seasons: int = 3) -> dict:
    seasons = sorted(df["season"].unique())
    preds: List[np.ndarray] = []
    trues: List[np.ndarray] = []
    season_used: List[int] = []

    for s in seasons:
        train = df[df["season"] < s].copy()
        test = df[df["season"] == s].copy()

        if train["season"].nunique() < min_train_seasons:
            continue

        train = train.dropna(subset=[ycol, "celebrity_age_during_season"])
        test = test.dropna(subset=[ycol, "celebrity_age_during_season"])
        if len(train) < 50 or len(test) < 5:
            continue

        X_train = make_X(train)
        X_test = make_X(test).reindex(columns=X_train.columns, fill_value=0)

        y_train = train[ycol].to_numpy(dtype=float)
        y_test = test[ycol].to_numpy(dtype=float)

        model = Ridge(alpha=alpha, random_state=0)
        model.fit(X_train, y_train)
        y_hat = model.predict(X_test)

        preds.append(y_hat)
        trues.append(y_test)
        season_used.append(int(s))

    if not preds:
        return {"pearson_r": np.nan, "rmse": np.nan, "n_test_total": 0, "n_seasons_tested": 0}

    yhat = np.concatenate(preds)
    ytrue = np.concatenate(trues)

    r = float(pearsonr(ytrue, yhat).statistic)
    rmse = float(math.sqrt(mean_squared_error(ytrue, yhat)))
    return {"pearson_r": r, "rmse": rmse, "n_test_total": int(len(ytrue)), "n_seasons_tested": int(len(season_used))}


def cv_table(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for outcome, y in OUTCOMES.items():
        res = season_forward_cv(df, y)
        rows.append({"outcome": outcome, **res})
    return pd.DataFrame(rows).sort_values("outcome").reset_index(drop=True)


# ----------------------------
# Main
# ----------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=str, required=True, help="Path to data_3.csv")
    ap.add_argument("--min_cat", type=int, default=6, help="Min count for industry/country to get its own one-hot")
    ap.add_argument("--outdir", type=str, default=".", help="Directory to write outputs (CSVs)")
    args = ap.parse_args()

    df = load_data(args.data)
    df = engineer_features(df, min_cat_count=args.min_cat)

    # 1) OLS fits
    ols_summary, fitted = fit_all_ols(df)
    key_coefs = extract_key_coefs(fitted, spec="base")

    # 2) Effect decomposition
    inc_r2 = incremental_r2_table(df)

    # 3) CV predictive Pearson r
    cv = cv_table(df)

    # save
    outdir = args.outdir
    ols_summary.to_csv(f"{outdir}/ols_summary.csv", index=False)
    key_coefs.to_csv(f"{outdir}/key_coefs_base.csv", index=False)
    inc_r2.to_csv(f"{outdir}/incremental_r2.csv", index=False)
    cv.to_csv(f"{outdir}/cv_forward_by_season.csv", index=False)

    # print concise console output
    pd.set_option("display.width", 140)
    pd.set_option("display.max_columns", 50)

    print("\n=== OLS summary (R2 etc.) ===")
    print(ols_summary)

    print("\n=== Key coefficients (base spec, robust SE) ===")
    print(key_coefs)

    print("\n=== Incremental R2 (variance contribution) ===")
    print(inc_r2)

    print("\n=== Forward CV by season (Ridge; Pearson r between y and y_hat) ===")
    print(cv)

    print("\nOutputs written to:", outdir)


if __name__ == "__main__":
    main()
